spring.application.name=siw-tornei-calcio
#==================================
# = Datasource
#==================================
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tornei_calcio
spring.datasource.username=sarabaranes
spring.datasource.password=postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#==================================
# = Web server
#==================================
server.port=8080
server.error.whitelabel.enabled=false
server.error.include-stacktrace=always
#==================================
# = Messages
#==================================
spring.messages.basename=messages/messages
spring.messages.encoding=ISO-8859-1
#==================================
# = Configuration File Caricamento Immagini
#==================================
# Dimensione massima del singolo file
spring.servlet.multipart.max-file-size=5MB
# Dimensione massima dell'intera richiesta HTTP
spring.servlet.multipart.max-request-size=5MB

# = Thymeleaf configurations
#==================================
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=ISO-8859-1

# cartella dove salviamo le immagini (relativa alla root del progetto)
upload.dir=uploads/